name: Generate Documentation from Commit Diff

on:
  push:
    branches:
      - develop

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          poetry install
          poetry run pip install ../generate_readme

      - name: Clone generate_readme repository
        run: |
          git clone https://github.com/YumaMatsumura/generate_readme.git
          cd generate_readme
          poetry install

      - name: Generate and commit documentation
        env:
          LANGUAGE: Japanese
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-2024-08-06
          TEMPLATE_PATH: ./template.json
          OUTPUT_PATH: ./README.md
          BRANCH_NAME: doc-update
        run: |
          cd generate_readme
          poetry run generate_readme

