name: Generate Documentation from Commit Diff

on:
  push:
    branches:
      - develop

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install openai

      - name: Clone package
        run: git clone https://github.com/YumaMatsumura/generate_readme.git

      - name: Generate and commit documentation
        env:
          LANGUAGE: ja
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-2024-08-06
          TEMPLATE_PATH: ./template.json
          OUTPUT_PATH: ./README.md
          BRANCH_NAME: doc-update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/YumaMatsumura/generate_readme_test.git

          python generate_readme/generate_readme.py

